import { goodElemType } from '../type/Objects';

export const arrayOfGoods: goodElemType[] = [
  {
    url: 'assets/Burberry_Summer_for_Women.jpg',
    name: 'Burberry Summer for Women',
    brand: 'Burberry',
    volume: 100,
    group: 'древесные',
    gender: ['женский'],
    popularity: false,
    price: 175,
    amount: 3,
    year: 2013,
  },

  {
    url: 'assets/Burberry_Tender_Touch.jpg',
    name: 'Burberry Tender Touch',
    brand: 'Burberry',
    volume: 50,
    group: 'цветочные',
    gender: ['женский'],
    popularity: false,
    price: 160,
    amount: 6,
    year: 2003,
  },

  {
    url: 'assets/Burberry_Tudor_Rose.jpg',
    name: 'Burberry Tudor Rose',
    brand: 'Burberry',
    volume: 50,
    group: 'древесные',
    gender: ['женский'],
    popularity: false,
    price: 100,
    amount: 2,
    year: 2017,
  },

  {
    url: 'assets/Byredo_Bal_dAfrique.jpg',
    name: "Byredo Bal d'Afrique",
    brand: 'Byredo',
    volume: 100,
    group: 'фруктовые',
    gender: ['мужской', 'женский'],
    popularity: false,
    price: 835,
    amount: 5,
    year: 2009,
  },

  {
    url: 'assets/Byredo_Gypsy_Water.jpg',
    name: 'Byredo Gypsy Water',
    brand: 'Byredo',
    volume: 100,
    group: 'древесные',
    gender: ['мужской', 'женский'],
    popularity: false,
    price: 910,
    amount: 1,
    year: 2008,
  },

  {
    url: 'assets/Carolina_Herrera_212_Sexy_Men.jpg',
    name: 'Carolina Herrera 212 Sexy Men',
    brand: 'Carolina Herrera',
    volume: 50,
    group: 'древесные',
    gender: ['мужской'],
    popularity: false,
    price: 160,
    amount: 4,
    year: 2006,
  },

  {
    url: 'assets/Carolina_Herrera_Sublime.jpg',
    name: 'Carolina Herrera Sublime',
    brand: 'Carolina Herrera',
    volume: 50,
    group: 'цветочные',
    gender: ['женский'],
    popularity: false,
    price: 160,
    amount: 4,
    year: 2013,
  },

  {
    url: 'assets/Carolina_Herrera_Very_Good_Girl.jpg',
    name: 'Carolina Herrera Very Good Girl',
    brand: 'Carolina Herrera',
    volume: 80,
    group: 'фруктовые',
    gender: ['женский'],
    popularity: true,
    price: 305,
    amount: 7,
    year: 2021,
  },

  {
    url: 'assets/Chanel_Coco_Mademoiselle.jpg',
    name: 'Chanel Coco Mademoiselle',
    brand: 'Chanel',
    volume: 100,
    group: 'фруктовые',
    gender: ['женский'],
    popularity: true,
    price: 620,
    amount: 8,
    year: 2001,
  },

  {
    url: 'assets/Chanel_Chanel_No_5_Red_Edition.jpg',
    name: 'Chanel Chanel No.5 Red Edition',
    brand: 'Chanel',
    volume: 100,
    group: 'цветочные',
    gender: ['женский'],
    popularity: false,
    price: 610,
    amount: 2,
    year: 2018,
  },

  {
    url: 'assets/Chloe_Chloe.jpg',
    name: 'Chloé Chloé',
    brand: 'Chloé',
    volume: 50,
    group: 'цветочные',
    gender: ['женский'],
    popularity: false,
    price: 430,
    amount: 8,
    year: 2008,
  },

  {
    url: 'assets/Chloe_Love.jpg',
    name: 'Chloé Love',
    brand: 'Chloé',
    volume: 50,
    group: 'цветочные',
    gender: ['женский'],
    popularity: false,
    price: 430,
    amount: 8,
    year: 2010,
  },

  {
    url: 'assets/Dior_Hypnotic_Poison.jpg',
    name: 'Dior Hypnotic Poison',
    brand: 'Dior',
    volume: 50,
    group: 'сладкие',
    gender: ['женский'],
    popularity: true,
    price: 325,
    amount: 9,
    year: 1998,
  },

  {
    url: 'assets/Dior_Jadore.jpg',
    name: "Dior J'adore",
    brand: 'Dior',
    volume: 100,
    group: 'цветочные',
    gender: ['женский'],
    popularity: true,
    price: 470,
    amount: 10,
    year: 1999,
  },

  {
    url: 'assets/Dior_Miss_Dior.jpg',
    name: 'Dior Miss Dior',
    brand: 'Dior',
    volume: 100,
    group: 'цветочные',
    gender: ['женский'],
    popularity: true,
    price: 390,
    amount: 11,
    year: 2012,
  },

  {
    url: 'assets/Dior_Miss_Dior_Blooming_Bouquet.jpg',
    name: 'Dior Miss Dior Blooming Bouquet',
    brand: 'Dior',
    volume: 100,
    group: 'цветочные',
    gender: ['женский'],
    popularity: false,
    price: 380,
    amount: 1,
    year: 2014,
  },

  {
    url: 'assets/Dior_Pure_Poison.jpg',
    name: 'Dior Pure Poison',
    brand: 'Dior',
    volume: 50,
    group: 'фруктовые',
    gender: ['женский'],
    popularity: false,
    price: 325,
    amount: 12,
    year: 2004,
  },

  {
    url: 'assets/Givenchy_Irresistible.jpg',
    name: 'Givenchy Irresistible',
    brand: 'Givenchy',
    volume: 80,
    group: 'фруктовые',
    gender: ['женский'],
    popularity: true,
    price: 220,
    amount: 12,
    year: 2020,
  },

  {
    url: 'assets/Givenchy_LInterdit.jpg',
    name: "Givenchy L'Interdit",
    brand: 'Givenchy',
    volume: 80,
    group: 'фруктовые',
    gender: ['женский'],
    popularity: true,
    price: 220,
    amount: 11,
    year: 2018,
  },

  {
    url: 'assets/Jo_Malone_London_English_Pear_&_Freesia.jpg',
    name: 'Jo Malone London English Pear & Freesia',
    brand: 'Jo Malone London',
    volume: 100,
    group: 'цветочные',
    gender: ['женский'],
    popularity: false,
    price: 330,
    amount: 10,
    year: 2010,
  },

  {
    url: 'assets/Jo_Malone_London_Wood_Sage_&_Sea_Salt.jpg',
    name: 'Jo Malone London Wood Sage & Sea Salt',
    brand: 'Jo Malone London',
    volume: 100,
    group: 'свежие',
    gender: ['женский', 'мужской'],
    popularity: false,
    price: 330,
    amount: 9,
    year: 2014,
  },

  {
    url: 'assets/Kilian_A_Taste_of_Heaven.jpg',
    name: 'Kilian A Taste of Heaven',
    brand: 'Kilian',
    volume: 100,
    group: 'свежие',
    gender: ['мужской'],
    popularity: false,
    price: 670,
    amount: 7,
    year: 2006,
  },

  {
    url: 'assets/Montale_Aoud_Amber_Rose.jpg',
    name: 'Montale Aoud Amber Rose',
    brand: 'Montale',
    volume: 100,
    group: 'древесные',
    gender: ['женский', 'мужской'],
    popularity: false,
    price: 230,
    amount: 8,
    year: 2010,
  },

  {
    url: 'assets/Tom_Ford_Black_Orchid.jpg',
    name: 'Tom Ford Black Orchid',
    brand: 'Tom Ford',
    volume: 100,
    group: 'древесные',
    gender: ['женский', 'мужской'],
    popularity: false,
    price: 820,
    amount: 6,
    year: 2006,
  },

  {
    url: 'assets/Victorias_Secret_Angel.jpg',
    name: "Victoria's Secret Angel",
    brand: "Victoria's Secret",
    volume: 100,
    group: 'фруктовые',
    gender: ['женский'],
    popularity: false,
    price: 200,
    amount: 5,
    year: 2011,
  },

  {
    url: 'assets/Victorias_Secret_Bombshell.jpg',
    name: "Victoria's Secret Bombshell",
    brand: "Victoria's Secret",
    volume: 100,
    group: 'фруктовые',
    gender: ['женский'],
    popularity: false,
    price: 350,
    amount: 2,
    year: 2010,
  },

  {
    url: 'assets/Victorias_Secret_Forbidden.jpg',
    name: "Victoria's Secret Forbidden",
    brand: "Victoria's Secret",
    volume: 100,
    group: 'фруктовые',
    gender: ['женский'],
    popularity: false,
    price: 275,
    amount: 3,
    year: 2014,
  },

  {
    url: 'assets/Victorias_Secret_Love_Spell.jpg',
    name: "Victoria's Secret Love Spell",
    brand: "Victoria's Secret",
    volume: 100,
    group: 'фруктовые',
    gender: ['женский'],
    popularity: false,
    price: 280,
    amount: 4,
    year: 2000,
  },

  {
    url: 'assets/Victorias_Secret_Sexy_Little_Things_Noir_Tease.jpg',
    name: "Victoria's Secret Sexy Little Things Noir Tease",
    brand: "Victoria's Secret",
    volume: 100,
    group: 'фруктовые',
    gender: ['женский'],
    popularity: false,
    price: 510,
    amount: 4,
    year: 2010,
  },
];
